# Generated by Django 4.2.5 on 2023-09-23 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('first_aid', 'First Aid'), ('cpr', 'CPR'), ('6m_criminal_record', '6m Criminal Record'), ('1yr_criminal_record', '1yr Criminal Record')], max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='staff',
            name='certs',
            field=models.ManyToManyField(to='student_management.certification'),
        ),
    ]
