# Generated by Django 4.2.5 on 2023-09-23 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management', '0002_certification_staff_certs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='certs',
            field=models.ManyToManyField(blank=True, to='student_management.certification'),
        ),
    ]
